config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  get 'faq', to: 'static_pages#faq', as: :faq
  get 'stats', to: 'static_pages#stats', as: :stats

  resources :games, except: [:edit, :update]
  resources :players

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :game_players
	has_many :players, through: :game_players
	has_many :scores, dependent: :destroy

  validates :game_date, presence: true

	accepts_nested_attributes_for :players

  def self.build_game_data(params)
    players = params["game"]["players_attributes"]
    team1 = { members: [], rating: 0, score: nil }
    team2 = { members: [], rating: 0, score: nil }
    winning_score = 0

    players.each do |key, value|
      score = value["score"]["score"].to_i
      name = value["name"]

      #assign winning teams and scores
      if not name.blank? 
        if team1[:members].empty? and team2[:members].empty?
          team1[:members] << name
          team1[:score] = score
        else
          if team1[:score] == score
            team1[:members] << name
          else
            team2[:members] << name
            team2[:score] = score
          end
        end

        if winning_score < score
          winning_score = score
        end
      end
    end

    #assign rating and find the rating change
    team1[:members].each do |member|
      team1[:rating] += Player.find_by_name(member).rating
    end

    team2[:members].each do |member|
      team2[:rating] += Player.find_by_name(member).rating
    end

    return team1, team2, winning_score
  end

  def update_rating(team1, team2, winning_score)
    if team1[:score] == winning_score
      winning_team = team1
      losing_team = team2
      win_percentage = team1[:score].to_f / (team1[:score] + team2[:score])
      rating_change = self.calc_rating_change(team1[:rating], team2[:rating], win_percentage)
    else
      winning_team = team2
      losing_team = team1
      win_percentage = team2[:score].to_f / (team1[:score] + team2[:score])
      rating_change = self.calc_rating_change(team2[:rating], team1[:rating], win_percentage) 
    end

    return rating_change
  end

  def calc_rating_change(winner_rating, loser_rating, win_percentage)
    expected_score = 1.0 / (1 + 10 ** ((loser_rating - winner_rating) / 400))
    rating_change = (32 * (1 - expected_score)).abs * (1.0 + (win_percentage-0.5))
    
    return rating_change
  end

  def find_winning_score
    winning_score = 0
    self.scores.each do |score|
      if score.score > winning_score
        winning_score = score.score
      end
    end

    return winning_score
  end

  def find_winning_player_ids
    winning_player_ids = []
    winning_score = self.find_winning_score
    self.scores.each do |score|
      if score.score == winning_score
        winning_player_ids << score.player_id
      end
    end

    return winning_player_ids
  end

  def box_score
    box_score = { winners: [], losers: [], winning_score: nil, losing_score: nil}
    winner_score = find_winning_score

    self.scores.each do |score|
      player_name = Player.find(score.player_id).name
      if score.score == winner_score
        box_score[:winners] << player_name
        box_score[:winning_score] = winner_score if box_score[:winning_score] == nil
      else
        box_score[:losers] << player_name
        box_score[:losing_score] = score.score if box_score[:losing_score] == nil
      end
    end

    return box_score
  end

  def is_championship_belt_game
    return self.players.any? {|p| p[:has_championship_belt] == true }
  end

  def send_slack_notification(team1, team2, winning_score)
    if team1[:score] == winning_score
      winning_team = team1
      losing_team = team2
    else
      winning_team = team2
      losing_team = team1
    end

    winning_team_name = winning_team[:members].join('/')
    winning_team_score = winning_team[:score]
    losing_team_name = losing_team[:members].join('/')
    losing_team_score = losing_team[:score]

    if losing_team_score == 0
      HTTP.post("#{Rails.application.config.slack_carvana_ping_pong_url}", 
              :json => { text: ":table_tennis_paddle_and_ball: #{winning_team_name} just DOMINATED #{losing_team_name} #{winning_team_score} - #{losing_team_score} :clap: :muscle: :rocket:" })
    else
      HTTP.post("#{Rails.application.config.slack_carvana_ping_pong_url}", 
              :json => { text: ":table_tennis_paddle_and_ball: #{winning_team_name} just won against #{losing_team_name} #{winning_team_score} - #{losing_team_score} :raised_hands:" })
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require "http"
  before_action :set_game, only: [:show, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.paginate(:page => params[:page], :per_page => 10)
                 .order(game_date: :desc, created_at: :desc)
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    gon.player_names = Player.find_all_player_names
    @game = Game.new(game_date: DateTime.now.to_date)
    
    4.times do
      player = @game.players.build
      4.times { player.scores.build }
    end 
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new
    @game.game_date = params["game"]["game_date"]
    @players = params["game"]["players_attributes"]
    player_count = 0

    team1, team2, winning_score = Game.build_game_data(params)

    #find winning and losing team and calculate rating change accordingly
    rating_change = @game.update_rating(team1, team2, winning_score)
    @game.rating_change = rating_change

    #calculate player wins, losses, ratings
    @players.each do |key, value|
      if value["name"] != ''
        p = Player.find_by_name(value["name"])
        player_count += 1
        @game.players << p
        score = value["score"]["score"].to_i
        score_params = Score.new({id: nil, game_id: @game.id, player_id: p.id, score: score})
        @game.scores << score_params
        
        if score == winning_score
          p.wins += 1
          p.rating += rating_change
          p.winning_streak += 1
          p.losing_streak = 0
        else
          p.losses += 1
          p.rating -= rating_change
          p.losing_streak += 1
          p.winning_streak = 0
        end
      end
    end

    #determine if it's a championship belt game
    if player_count == 2
      is_championship_belt_game = @game.is_championship_belt_game
    else
      is_championship_belt_game = false
    end

    #determine who has the new championship belt
    if is_championship_belt_game
      winning_player_ids = @game.find_winning_player_ids

      @game.players.each do |p|
        #has belt and lost
        if (p.has_championship_belt) && (not winning_player_ids.include? p.id)
          p.has_championship_belt = false
        end
        #doesn't have belt and won
        if (p.has_championship_belt == false) && (winning_player_ids.include? p.id)
          p.has_championship_belt = true
        end 
      end
    end

    #save data
    respond_to do |format|
      if @game.save
        @game.players.each do |p|
          p.save
        end
        @game.scores.each do |s|
          s.save
        end

        @game.send_slack_notification(team1, team2, winning_score)

        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { 4.times do
                        player = @game.players.build
                        4.times { player.scores.build }
                      end 
                      render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    
    #find winning score
    winning_score = @game.find_winning_score

    #reverting score and ratings
    @game.scores.each do |score|
      p = Player.find(score.player_id)

      if score.score == winning_score
        p.wins -= 1
        p.rating -= @game.rating_change
      else
        p.losses -= 1
        p.rating += @game.rating_change
      end
      p.save
    end

    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_date, 
                                    players_attributes: [:id, :name, :score])
    end

    def destroy_scores
      self.scores.delete_all
    end
end

app/helpers/games_helper.rb
module GamesHelper

end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
      <% @game.errors.full_messages.each do |message| %>
        <p class="alert alert-danger"><%= message %></p>
      <% end %>
  <% end %>
  
  <div class="field form-group">
    <%= f.label :game_date %>
    <%= f.date_field :game_date, class: "form-control" %><br />
  </div>

  <p><strong>Match Score</strong></p>
    <%= f.fields_for :players do |builder| %>
      <%= render "player_fields", :f => builder %>
    <% end %>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/games/_player_fields.html.erb
 <div class="form-inline">
  <div class="field form-group">
	<%= f.text_field :name, class: "name form-control", placeholder: "Player Name" %>

	<%= f.fields_for :score do |builder| %>
		<%= render 'score_fields', :f => builder %>
	<% end %>
	</div>
</div>

app/views/games/_score_fields.html.erb
<div class="field form-group">
	<%= f.number_field :score, class: "form-control", placeholder: "Games Won" %> <br />
</div>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Log
  <span class="btn-group">
    <%= button_to 'New Game', new_game_path, method: :get, class: "btn btn-info" %>
  </span>
</h1>

<h5><%= Game.all.count %> games played</h5>
<table class="table">
  <thead>
    <tr>
      <th>Winners</th>
      <th>Losers</th>
      <th>Winner Score</th>
      <th>Loser Score</th>
      <th>Game Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.box_score[:winners].join(", ") %></td>
        <td><%= game.box_score[:losers].join(", ") %></td>
        <td><%= game.box_score[:winning_score] %></td>
        <td><%= game.box_score[:losing_score] %></td>
        <td><%= game.game_date %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure? This will remove the game from existence.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @games %>

app/views/games/new.html.erb
<div class="row">
<div class="col-md-5">
	<h1>New Game</h1>

  
	<%= render 'form' %>
	
	<%= link_to 'Back', games_path %>

</div>

<div class="col-md-5 col-md-offset-1">
	<h3>Instructions</h3>
	<p>Under Match Score, input the following for each player:</p>
	<ol>
		<li><strong>Player Name:</strong> input each player's name into text box. If no match found in auto-complete, you must first create the player under Players section. Otherwise, form submission will fail.</li>
		<li><strong>Games Won:</strong> For each player in the match, input the number of games the player won in the series. If Bob and Rachel played 3 games series, where Bob won 2 and Rachel won 1. Then type 2 for Bob and 1 for Rachel.</li>
	</ol>
	<p>Afterwards, click on Create Game to save results</p>
	<p><strong>Note:</strong> If this is a doubles game, input the same number of games won for both you and your teammate. For example, if Bob and Rachel won against Kevin and Emily 2-1, then you would put 2 under Bob and Rachel and 1 under Kevin and Emily.</p>
</div>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @game.game_date %>
</p>

<p>
  <strong>Rating change:</strong>
  <%= @game.rating_change %>
</p>


<%= link_to 'Back', games_path %>