config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  get 'faq', to: 'static_pages#faq', as: :faq
  get 'stats', to: 'static_pages#stats', as: :stats

  resources :games, except: [:edit, :update]
  resources :players

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carvana Ping Pong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--Google Analytics Script -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-82909400-1', 'auto');
    ga('send', 'pageview');
  </script>

</head>
<body>
  <%= include_gon(:init => true) %>
  <div id="wrapper">
  	<div id="sidebar-wrapper">
  		<ul class="sidebar-nav">
        <%= image_tag("CarvanaPingPong.png") %>
  			<li><%= link_to "Players", players_path %></li>
  			<li><%= link_to "Games", games_path %></li>
        <li><%= link_to "Stats", stats_path %></li>
        <li><%= link_to "FAQ", faq_path %>
  		</ul>

    </div>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                  <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">
                    Menu
                  </a>
  
									<%= yield %>
                </div>
            </div>
        </div>
    </div>
  	
  </div>
  
  <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>
</html>